// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    TreeList: typeof import('D:/treeNodes/src/components/TreeList.vue')['default']
    TreeNode: typeof import('D:/treeNodes/src/components/TreeNode.vue')['default']
  }
}

export { }
